# Generated by Django 4.2.1 on 2023-07-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='superUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('speciality', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=60)),
            ],
        ),
    ]
