# Generated by Django 4.2.1 on 2023-10-24 07:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
