# Generated by Django 4.2.1 on 2023-10-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='examiner',
        ),
    ]
