# Generated by Django 4.2.1 on 2023-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='rpdNLA_endT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLA_reason',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLA_startT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLA_wrongAns',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLB_endT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLB_reason',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLB_startT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='rpdNLB_wrongAns',
            field=models.IntegerField(null=True),
        ),
    ]
