# Generated by Django 4.2.1 on 2023-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='stage',
            field=models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('BOTH', 'Primary/Secondary')], default='PRIMARY', max_length=20),
        ),
    ]
