# Generated by Django 4.2.2 on 2023-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
