# Generated by Django 4.2.2 on 2024-08-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalReportPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1_skill_sound', models.BooleanField(null=True)),
                ('test_2_skill_sound', models.BooleanField(null=True)),
                ('test_3_skill_speed', models.BooleanField(null=True)),
                ('test_4_skill_speed', models.BooleanField(null=True)),
                ('test_5_skill_memory', models.BooleanField(null=True)),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('result', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_ids', to='primary.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ids', to='primary.student')),
            ],
        ),
    ]
