# Generated by Django 4.2.1 on 2023-07-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='superUsers',
            new_name='Examiner',
        ),
    ]
