# Generated by Django 4.2.1 on 2023-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_alter_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=60),
        ),
    ]
