# Generated by Django 4.2.9 on 2024-09-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_finalreportprimary'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalReportSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('results', models.TextField()),
                ('suggestion', models.TextField()),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_idS', to='primary.examiner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_idS', to='primary.student')),
            ],
        ),
    ]
