# Generated by Django 4.2.2 on 2023-07-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("primary", "0002_rename_superusers_examiner"),
    ]

    operations = [
        migrations.RemoveField(model_name="examiner", name="confirm_password",),
    ]
