# Generated by Django 4.2.2 on 2024-01-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_score_rpdnla_endt_score_rpdnla_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='rpdNLA_endT',
            new_name='endT',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rpdNLA_reason',
            new_name='parts_name',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rpdNLB_reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rpdNLA_startT',
            new_name='startT',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='rpdNLA_wrongAns',
            new_name='wrongAns',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNLB_endT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNLB_startT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNLB_wrongAns',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOA_endT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOA_reason',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOA_startT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOA_wrongAns',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOB_endT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOB_reason',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOB_startT',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rpdNOB_wrongAns',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=60, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='primary.student')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_id', to='primary.test'),
        ),
    ]
