# Generated by Django 4.2.1 on 2023-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_rpdnamingobj_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpdnamingobj',
            name='statusB',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
