# Generated by Django 4.2.9 on 2024-05-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_nonwordrepetitionsec'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpdNamingObjSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startT_A', models.DateTimeField(null=True)),
                ('endT_A', models.DateTimeField(null=True)),
                ('wrongAns_A', models.IntegerField(null=True)),
                ('reason_A', models.CharField(max_length=60, null=True)),
                ('startT_B', models.DateTimeField(null=True)),
                ('endT_B', models.DateTimeField(null=True)),
                ('wrongAns_B', models.IntegerField(null=True)),
                ('reason_B', models.CharField(max_length=60, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.student')),
            ],
        ),
    ]
