# Generated by Django 4.2.9 on 2024-06-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_rpdnamingobjsec'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWordReadingAccSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAns', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=60, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.student')),
            ],
        ),
    ]
