# Generated by Django 4.2.1 on 2023-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_rpdnamingobj_statusb'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpdnamingobj',
            name='durationB',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rpdnamingobj',
            name='end_timeB',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='rpdnamingobj',
            name='reasonB',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='rpdnamingobj',
            name='start_timeB',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='rpdnamingobj',
            name='timeWrngAnsB',
            field=models.IntegerField(null=True),
        ),
    ]
