# Generated by Django 4.2.1 on 2023-12-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_rpdnamingobj_durationb_rpdnamingobj_end_timeb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpdNOA_startT', models.TimeField(null=True)),
                ('rpdNOA_endT', models.TimeField(null=True)),
                ('rpdNOA_wrongAns', models.IntegerField(null=True)),
                ('rpdNOA_reason', models.CharField(max_length=60, null=True)),
                ('rpdNOB_startT', models.TimeField(null=True)),
                ('rpdNOB_endT', models.TimeField(null=True)),
                ('rpdNOB_wrongAns', models.IntegerField(null=True)),
                ('rpdNOB_reason', models.CharField(max_length=60, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.student')),
            ],
        ),
        migrations.DeleteModel(
            name='rpdNamingObj',
        ),
    ]
