# Generated by Django 4.2.2 on 2023-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primary", "0005_score_delete_rpdnamingobj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="rpdNOA_endT",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOA_startT",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOB_endT",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOB_startT",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
