# Generated by Django 4.2.2 on 2023-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primary", "0006_alter_score_rpdnoa_endt_alter_score_rpdnoa_startt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="rpdNOA_endT",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOA_startT",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOB_endT",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="rpdNOB_startT",
            field=models.DateTimeField(null=True),
        ),
    ]
